config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users, only: [:new, :create, :show]
  resources :events, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new]
  get 'signup'        => 'users#new'
  get 'login'         => 'sessions#new'
  post 'login'        => 'sessions#create'
  delete 'logout'     => 'sessions#destroy'
  root 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :host, :class_name => 'User'

  has_many :invitations, :foreign_key => :attended_event_id
  has_many :attendees, :through => :invitations

  scope :past,      -> { where("date < ?", Time.now) }
  scope :upcoming,  -> { where("date > ?", Time.now) }

  # def self.upcoming
  #   self.where("date > ?", Time.now)
  # end

  # def self.past
  #   self.where("date < ?", Time.now)
  # end


end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :attended_event, :class_name => 'Event'
  belongs_to :attendee,       :class_name => 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :hosted_events, :foreign_key => 'host_id', :class_name => 'Event'

  has_many :invitations, :foreign_key => :attendee_id
  has_many :attended_events, :through => :invitations

  has_secure_password


  def upcoming_events
    attended_events.where("date > ?", Time.now)
  end

  def past_events
    attended_events.where("date < ?", Time.now)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    include SessionsHelper

    before_filter :require_login

    private

      def require_login
        unless current_user
          redirect_to login_url
        end
      end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    @upcoming_events = @events.upcoming
    @past_events = @events.past

  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Event created!"
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:description, :host_id, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'form', only: [:new]
  skip_before_filter :require_login

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "Logged in!"
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'form', only: [:new]
  skip_before_filter :require_login, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User created!'
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events =  @user.upcoming_events
    @past_events = @user.past_events
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
      session[:user_id] = user.id
    end

    def current_user
      user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    end

    def logged_in?
      !current_user.nil?
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
      flash[:info] = 'Logged out'
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<%= label_tag :created_by %>
<p><%= link_to "#{event.host.name}", user_path(event.host) %> </p>


<%= label_tag :date %>
<%= content_tag :p, "#{event.date}" %>

<%= label_tag :description %>
<%= content_tag :p, "#{event.description}" %>

<%= label_tag :attending %>
<ul>
<% event.attendees.each do |attendee| %>
  <li> <%= link_to "#{attendee.name}", user_path(attendee) %></li>
<% end %>
</ul>

app/views/events/_header.html.erb
      <div class="blog-header">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
      </div>

app/views/events/_spacer.html.erb
<hr>

app/views/events/index.html.erb
<h1>Upcoming events</h1>
<%= render partial: @upcoming_events, spacer_template: "events/spacer"  %>
<h1>Past events</h1>
<%= render partial: @past_events,  spacer_template: "events/spacer"  %>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
  <%= form_for(@event) do |f| %>

    <%= f.hidden_field :host_id, value: "#{User.first.id}" %>

    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', rows: 5 %>

    <%= f.label :date %>
    <%= f.datetime_field :date, class: 'form-control', min: Date.today %>

    <%= f.submit 'Create Event', class: "btn btn-primary", id: 'form-btn'  %>

  <% end %>
  </div>
</div>

app/views/events/show.html.erb
<%= label_tag :date %>
<%= content_tag :p, "#{@event.date}" %>

<%= label_tag :description %>
<%= content_tag :p, "#{@event.description}" %>

<%= label_tag :attending %>
<ul>
<% @event.attendees.each do |attendee| %>
  <li> <%= link_to "#{attendee.name}", user_path(attendee) %></li>
<% end %>
</ul>

app/views/layouts/_footer.html.erb
    <footer class="blog-footer">
      <p>Created using <a href="http://getbootstrap.com">Bootstrap</a></p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

app/views/layouts/_navigation.html.erb
    <div class="blog-masthead">
      <div class="container" id='nav-bar'>
        <nav class="blog-nav">
        <%= link_to 'Home', root_url, class: "blog-nav-item active" %>
        <%= link_to 'New Event', new_event_path, class: "blog-nav-item active" %>
        </nav>
      </div>
    </div>

app/views/layouts/_side_bar.html.erb
<div class="sidebar-module sidebar-module-inset">
  <h3> <%= link_to "#{current_user.name}", user_path(@current_user) %></h3>
  <%= link_to "Logout", logout_path, method: 'delete' %>
  </div>
<div class="sidebar-module">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/navigation' %>
      <div class="container">
           <div class="row">
              <div class="col-sm-8 blog-main">
                <%= yield %>
              </div>
              <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
                <%= render 'layouts/side_bar' %>
              </div>
            </div> <!-- row -->
      </div><!-- container -->
      <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/sign_in_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/users/new.html.erb
<div class="container form" id="sign-up">
<%= form_for @user, :html => { class: 'form-signin' } do |f| %>
  <%= content_tag :h2, "Create an account", class: "form-signin-heading" %>


  <%= f.text_field :name , class: "form-control", placeholder: 'Name' %>

  <%= f.email_field :email , class: "form-control", placeholder: 'Email' %>

  <%= f.password_field :password , class: "form-control" , placeholder: 'Password'%>
  <%= f.password_field :password_confirmation , class: "form-control", placeholder: 'Confirmation'%>

  <%= f.submit 'Create Account',  class: "btn btn-lg btn-primary btn-block" %>

<% end %>

 </div>

app/views/users/show.html.erb
<%= label_tag :name %>
<%= content_tag :p, "#{@user.name}" %>

<%= label_tag :email %>
<%= content_tag :p, "#{@user.email}" %>

<ul>
<%= label_tag :upcoming_events %>
  <% @upcoming_events.each do |event| %>
    <li>
      <%= link_to "<<", event_path(event) %>
      <%= "#{event.date}, hosted by #{event.host.name}" %>
    </li>
  <% end %>
</ul>
<ul>
<%= label_tag :past_events %>
  <% @past_events.each do |event| %>
    <li>
      <%= link_to "<<", event_path(event) %>
      <%= "#{event.date}, hosted by #{event.host.name}" %>
    </li>
  <% end %>
</ul>